#!/bin/bash -e
input_file=$1
input_name=$(basename "$input_file" .lyx)
test -n "$1"

tmp=$(mktemp -t lyx-mw-XXXXXX)
trap 'rm -rf "$tmp"' EXIT
msg() { printf >&2 '%s\n' "$*"; }

msg "Exporting to LaTeX format..."
lyx --export latex "$input_file"

msg "Converting to UTF-8..."
iconv -f ISO-8859-15 -t UTF-8 "$input_name".tex >"$tmp"

msg "Replacing missing texvc sequences..."
sed -i 's/\\coloneqq/:=/g; s/\\eqqcolon/=:/g' "$tmp"
sed -i 's/\{aligned}/{align}/g' "$tmp"

msg "Exporting to MediaWiki format..."
pandoc -f latex -t mediawiki -o "$input_name".mw "$tmp"
